oceanprotocol/docs

src/components/Repositories/Repository.jsx
=> fix for showing links on all repos

package.json, src/components/Header.module.scss, src/components/HeaderHome.module.scss
=> switch to mantaray backgrounds

scripts/deploy.sh
More closely following https://www.gatsbyjs.org/docs/caching/ to set correct caching headers on S3.
closes #65
=> different caching tactic

data/sections.yml, src/pages/index.jsx, src/pages/index.module.scss
=> teaser for API references

content/setup/marketplace.md
Also update what's said about the testnets, and link to the new page about testnets.
Don recommended I add the caveat, and I added the update re/ testnets since we now know more about them.
=> Add caveat re/ marketplace setup

data/sidebars/tutorials.yml
The tutorial itself comes from the dev-ocean repository / submodule. It was written in pull request https://github.com/oceanprotocol/dev-ocean/pull/99
=> Include the tutorial "Create Azure Credentials for Brizo"

content/concepts/contributing.md
I asked Sheridan if it would make sense to add links about the Ambassador Program in the page about ways to contribute, and he said it would.
=> Add links re/ the Ambassador Program

content/setup/marketplace.md, data/sidebars/tutorials.yml, src/components/Header.module.scss, src/components/HeaderHome.module.scss
Also update the dev-ocean submodule so that the docs show the latest Azure Storage tutorial.
=> Link to Azure setup tutorial from marketplace setup page

src/components/Repositories/RepositoryList.module.scss
Adding some solutions to address #80, mainly a bigger scrollbar which can be grabbed more easily.
=> Quick fixes for front-page repo list

content/tutorials/get-ether-and-ocean-tokens.md, content/tutorials/wallets.md, data/sidebars/tutorials.yml
@innoprenuer Here is that new Ocean Protocol docs page we discussed, to help people get a wallet that can hold Ocean Tokens.
=> Add tutorial about wallets for Ocean Tokens

src/components/DocContent.module.scss
=> Be more specific with inline code

content/concepts/introduction.md
- remove Business Whitepaper, replace with Business Strategy
- direct users to papers section (to keep papers downloads measurable in one place)
=> update papers section

content/tutorials/wallets.md, src/styles/global.scss
Last PR was closed because I couldn't figure out what the issue was
=> Updating wallets w/ formatting changes + grammar

content/concepts/testnets.md
In case someone is wondering what the "Spree Testnet" is, and how it relates to the other Testnets.
=> Add note re/ Spree Testnet on Testnets page

.travis.yml, scripts/deploy.sh
Let's try this and see what happens. It's an attempt to deal with issue #165
=> Get Travis to use python3 and pip3

content/concepts/terminology.md
...in the Terminology page.
Also note that Service Execution Agreements are also referred to as Service Agreements.
=> Link from SEA definition to OEP-11

content/concepts/testnets.md, content/concepts/wallets.md, content/tutorials/connect-to-networks.md, content/tutorials/introduction.md, content/tutorials/wallets-and-ocean-tokens.md, data/sidebars/tutorials.yml
1. Connect to Ocean-Related Networks
2. Teach Your Wallet to Track Ocean Tokens
Also updated the concepts pages about "Testnets" and "Wallet Basics".
Also split the tutorials into more groups, and rewrote the introduction to all the tutorials.
=> Add two new tutorials re/ wallets

content/tutorials/react-publish-data-set.md
- Updated the example asset. I got the new one from https://github.com/oceanprotocol/Plecos/blob/master/plecos/samples/sample_metadata_local.json 
- Fixed the spelling of "submitted" (was "submited")
=> Fix the Publish page of the React App Tutorial

content/concepts/components.md
as suggested in [a review of pull request](https://github.com/oceanprotocol/docs/pull/186#pullrequestreview-217843158) where I added a section about how to "Develop a Service Integration Driver or Plugin".
=> Add more about the OceanDB & Osmosis drivers in the "Components" page

content/tutorials/get-ether-and-ocean-tokens.md
Sebastian added that option (and I am grateful) but I only got around to copy-editing it just now.
=> Copy-edit Option 2 for getting ETH in Spree

content/concepts/testnets.md, content/tutorials/connect-to-networks.md
This is based on my own experience with finding the information needed to connect to the Nile Testnet, while trying out the Commons Marketplace (which is connected to the Nile Testnet).
The specific suggestions for "Symbol" and "Nickname" are because I realized it's not nice to tell people to put whatever they like. They don't know what a good example might be.
=> Give more help with connecting to Nile Testnet

content/concepts/wallets.md, content/setup/keeper.md
Hat tip to Trent who noticed one of these. I did a search for others and found a second one.
=> Fix two incorrect "localhost" URLs

config.js, src/components/Footer.jsx
=> use capitalized writing for social key names

config.js
new telegram link
@emilyellen should approve this as well
=> updated telegram link

src/components/Seo.jsx, src/pages/404.jsx, src/pages/index.jsx, src/templates/Doc.jsx, src/templates/Swagger/index.jsx, src/templates/Typedoc/index.jsx
=> prevent search engine indexing except for live

content/concepts/papers-blog-video-events.md, data/sidebars/concepts.yml
I also changed the sidebar label of the Introduction page to "Introduction"
=> Add new RESOURCES subsection with an empty page

src/templates/Doc.jsx
=> restrict depth of table of contents

README.md
We wouldn't want to forget squid-js!
=> squid-js is also a git submodule

content/concepts/ocean-tokens.md, content/concepts/resources.md, content/concepts/terminology.md, content/concepts/vulnerabilities.md, content/setup/marketplace.md, content/tutorials/amazon-s3-for-brizo.md, content/tutorials/get-ether-and-ocean-tokens.md, content/tutorials/metamask-setup.md, content/tutorials/on-premise-for-brizo.md, content/tutorials/react-get-use-data-set.md, src/components/DocContent.module.scss, src/styles/_code.scss
Use `blockquote` as a note style for important remarks, resulting in:
Update some content docs with this style for paragraphs intended as a note to users.
=> new note style

content/concepts/tools.md, content/tutorials/get-ether-and-ocean-tokens.md, data/repositories.yml
Generally present Barge as a tool, and clarify Faucet usage for Spree.
=> Update Barge and Faucet mentions

content/concepts/tools.md, data/repositories.yml
Link to status.oceanprotocol.com and its repo.
=> add status repo to tools

content/concepts/components.md, content/concepts/terminology.md, data/repositories.yml
=> document Events Handler

content/concepts/components.md, content/concepts/wallets.md, content/setup/marketplace.md, content/setup/quickstart.md, content/test.md, content/tutorials/example-code.md, content/tutorials/react-setup.md, data/repositories.yml, docs/repositories.md
Following https://github.com/oceanprotocol/barge/pull/189
=> switch Pleuston for Commons in most places

content/concepts/tools.md, data/repositories.yml
Mention IPFS node & gateway under Tools.
=> add IPFS to Tools

config.js, content/concepts/contributing.md, content/concepts/legal-reqs.md, src/components/DocFooter.jsx, src/components/Footer.jsx
- Replaced Gitter with Discord as main dev channel
- Removed Gitter labels + links
- Added Port in footer
=> removed gitter + added port

content/concepts/ocean-tokens.md
Added balancer, uniswap, vcc, gate.io
=> added missing exchanges

config.js
fix for 
https://github.com/oceanprotocol/docs/issues/473
=> fix bug by adding redirect

content/concepts/network-ethmainnet.md, content/concepts/network-rinkeby.md, content/concepts/network-ropsten.md
For https://github.com/oceanprotocol/ocean.py/issues/92#issuecomment-756251597
=> Point to proper locations of deployments

content/concepts/contributing.md
Preview: https://betadocs.oceanprotocol.com/concepts/contributing/
=> Extend contribution instructions

content/concepts/projects-using-ocean.md
* added new projects using Ocean
* removed date column since its not useful in this context
Fixes # .
- 
- 
-
=> added new projects using ocean

content/concepts/projects-using-ocean.md
Updated the list with an Entry for Evotegra.
=> Updated Evotegra as Project using Ocean

content/tutorials/wallets-and-ocean-tokens.md
There have been some requests about providing mOCEAN details to add in Metamask as custom token. So added this in the doc.
=> added mOCEAN details

content/tutorials/compute-to-data.md
=> update c2d install instructions

src/templates/MarkdownList.jsx
Towards #631
- Fix issue related to selected module.
=> Fixes issue related to selected module when user clicks on sidebar

content/tutorials/bsc-bridge.md
Towards #662  - need to replace Polygon content in this file
=> Issue662B 

content/concepts/networks.md, content/tutorials/wallets-and-ocean-tokens.md, content/tutorials/wallets.md
=> Issue 691 Mumbai 2

content/concepts/networks.md
=> Update networks.md for Mumbai typo

content/tutorials/marketplace-introduction.md, content/tutorials/marketplace-publish-data-asset.md, content/tutorials/marketplace-swap-and-stake.md, content/tutorials/marketplace.md
Fixes #686
- Fix spelling errors.
=> Fix: Spelling errors

data/sidebars/references.yml
Partly Fixes #678.
- Remove React and provider-py references
=> Remove react and provider-py references

content/concepts/oeps-asset-ddo.md, content/concepts/oeps-did.md, data/sidebars/concepts.yml, gatsby-node.js, src/components/Deployments.jsx
Fixes #701 
- Add Deployment version page
- Copy OEPs markdowns: Asset DDO and DID
=> Issue 701 - add deployment version, copy OEP markdowns

config.js, gatsby-node.js
Fixes #716
- Change Swagger url for Aqaurius
=> Feature: Update swagger spec urls

content/concepts/ddo-metadata.md
=> Issue 727 - make it easier to delineate required vs optional

README.md
Do a 'touch' to trigger rebuild
I'd changed the did and ddo mds. But they did't propagate to docs.oceanprotocol.com yet. This is a "touch" to trigger a rebuild.
=> "Touch" to trigger rebuild

content/concepts/compute-to-data.md
Fixes #738 - broken OEP12 link
=> Fix issue 738 - OEP12 link

content/concepts/compute-to-data.md
Fix #740 - c2d readability issues
=> For issue 740 - c2d readability issues

content/tutorials/compute-to-data-minikube.md, content/tutorials/compute-to-data.md, data/sidebars/tutorials.yml
Add Minikube install instructions as well as C2D config. Add menu item under Compute-To-Data.
=> mPowered round7

src/templates/Swagger/Toc.jsx
Fixes #715
- Handle `Aquarius` and Other REST apis.
=> Issue-715: Fix REST api issue for Provider

content/concepts/quickstart.md
Fixes #764
- Update ocean.js quickstart link
=> Issue-#764: Update Ocean.js quickstart link

src/components/Repository/index.jsx
Fixes #766
- Handle draft releases.
=> Issue-#766: Remove draft releases

content/tutorials/compute-to-data-algorithms.md
Work on #770.
Doesn't address the point about Docker image not found (not sure if it will be addressed inside docs, though).
=> Add some details to c2d tutorial.

src/components/Repository/index.jsx
Towards https://github.com/oceanprotocol/ocean.py/issues/497
=> Trigger rebuild to deploy ocean.py v0.7.0 docs

src/components/Search/SearchClient.jsx, src/components/Search/SearchComponent.jsx
Fixes #776
- Add Py module docs to search index
=> Issue-#776: Add py module docs to search index

content/concepts/networks.md
Fixes #755
- [Mumbai network] Add Ocean token faucet link
- Other readme improvements
=> Issue-#755: Add link for Mumbai Ocean token Faucet

content/concepts/projects-using-ocean.md
=> For #700. Make projects-using-ocean easy to maintain

data/repositories.yml
Fixes #786 - remove react from drivers
=> Fix #786 - remove react from drivers

content/concepts/networks.md
=> add moonriver

content/concepts/networks.md
Fixes #787
- Faucet url: do in new issue #807
=> Issue-#787: Add Celo testnet support

content/tutorials/marketplace-publish-data-asset.md
Fixes #803
- Fix spelling mistake
=> Issue-#803: Fix spelling mistakes

content/concepts/did-ddo.md
Fixes #805
- Fix spelling mistake
=> Fix spelling mistake

content/concepts/compute-to-data.md
=> Improve C2D links

content/concepts/did-ddo.md
=> Add nft.tokenURI

content/concepts/did-ddo.md
Fixes #886
- Create nested html tables to fix accommodate `description` and avoid horizontal scroll.
=> Issue:#886: Refactor table structure

content/tutorials/compute-to-data-minikube.md
Fixes #903 
- Add optional egress deployment command with note
=> Issue-#903: Add egress deployment command in c2d

config.js, content/concepts/compute-to-data.md
=> Issue-#910: Fix broken link

data/sidebars/concepts.yml
Fixes #916
- Remove duplicate link for "DID & DDOs" page
=> Issue-#916: Remove duplicate links

content/concepts/introduction.md
Fixes #909
- Update introduction page for v4
=> Update introduction page for v4

content/concepts/networks.md
- remove all networks which don't have v4 smartcontracts deployed
- set correct URLs
=> V4: update network list

gatsby-node.js
Fixes #921
- Ocean.js api references for v4
- Ocean.py api references for v4
=> V4: Ocean.js and Ocean.py api references

content/concepts/introduction.md
Fixes #934
- Update introduction page content
=> Issue:#934: Introduction page content

content/concepts/networks.md
Fixes #924 .
- Changed the link of address.json
=> Updated contracts address.json file link

.markdownlint.json
=> Fix linter issues

src/components/@shared/atoms/Badge.jsx, src/components/@shared/atoms/Badge.module.scss, src/components/Header.jsx, src/components/HeaderHome.jsx, src/styles/_variables.scss
=> Add v4 version badge

content/concepts/roles.md
Fixes #955
- Use a tick mark character that works on all browsers
=> Issue-#955: Fix tick marks

content/concepts/architecture.md
Deleted superfluous information.
Fixes # .
- 
- 
-
=> Fixed grammar

content/tutorials/compute-to-data-minikube.md
Fixes #872
- Add information about minikube start options
=> Issue-#872: Add information about minikube start options

content/concepts/did-ddo.md
Fixes #1004 .
- Update consumerParameters section of DDO spec, specify type/required for each attribute
=> Issue #1004 specify consumer parameters type and required

content/concepts/did-ddo.md
- update ddo schema to 4.1.0
- add headers object to storage type 'url'
PS: Probably needs some content writing
=> Update DDO spec to v4.1.0

content/references/introduction.md
Fixes #1000
- Remove reference to react lib in References introduction
=> Issue-#1000: Remove react lib

src/components/Search/SearchComponent.jsx
Fixes #1050
- Index only ocean.py and provider pydocs for searching
=> Index only ocean.py, provider pydocs, ocean-subgraph for searching

config.js, src/components/HeaderHome.jsx, src/components/HeaderHome.module.scss
Fixes #1061
- Update home page and mention about changes in Ocean Market
- Add link to blog post
=> Update home page

config.js, content/concepts/architecture.md, content/tutorials/compute-to-data-datasets-algorithms.md
Fixes:  https://github.com/oceanprotocol/aquarius/issues/851
- Fix broken links
=> Fix broken link to did-ddo page

README.md
Fixes #1071 
- Adding a supporters section and mentioning gitbook in readme.md
=> Adding a supporters section and mentioning gitbook in readme.md

SUMMARY.md, building-with-ocean/README.md, building-with-ocean/build-a-marketplace/customising-your-market.md, using-ocean-market/README.md
- Making sure the Ocean is capitalised
- Improving the main page about using ocean marketplace page
- Updating the alternative text on some of the images
=> Minor improvements

SUMMARY.md
=> Fix link to page on bridges

core-concepts/networks/bridges.md
Fixes broken links to images in bridges page.
- Update path to images
=> Fix broken images

building-with-ocean/compute-to-data/compute-to-data-architecture.md
**Changes in this PR**
- Changed spaces to `%20`.
- Removed `\` character.
- Added correct relative image path.
=> Fix: Sequence diagram for new compute job not visible

core-concepts/contributing.md
Fixes #1103 
- Updating the funding section to mention shipyard and data bounties
=> Updating the funding section

building-with-ocean/build-a-marketplace/deploying-market.md
Fixes #1084 
- Updating deployment instructions for next.js static deployment
=> Updating deployment instructions for next.js static deployment

core-concepts/datanft-and-datatoken.md
=> Add section on templateId

core-concepts/datanft-and-datatoken.md, core-concepts/roles.md
Fixes #1115 
I realised that there is quite a lot of information that is missing from our docs about Data NFTs. Giving that the docs is the main place come to look for this information, I thought I would move it here. This page might be getting a bit long though, so we could split it up.
- Adding fractional ownership content
- Adding additional info on roles
- More info on what a Data NFT is
- More information about our implementation of a Data NFT
=> Extra Info on Data NFTs

core-concepts/asset-pricing.md
Changing 3 to two to reflect the removal of dynamic pricing
-
=> Update number of pricing structures

core-concepts/did-ddo.md
- Fixes #1141 .
- adding asset state 5 (asset delisted)
=> adding state

building-with-ocean/using-ocean-subgraph/README.md, core-concepts/networks.md
Fixes #1148  .
- removed Moonbase network.
=> Removed Moonbase network.

api-references/aquarius-rest-api.md, api-references/provider-rest-api.md
Fixes #1104 .
- updated `provider-api.md`;
- reorder endpoints to be clearer how to use;
- update aqua examples
=> Added context to the backend components API.

core-concepts/did-ddo.md
Fixes #1159 
- Updating state descriptions
=> Updating state descriptions

core-concepts/did-ddo.md
Fixes #1161
- Fixing a formatting issue where the following title was included as part of the table.
Preview [here](https://ocean-protocol.gitbook.io/1162-formatting-fix/iXLmxw0mpe0FX8JDEgBD/core-concepts/did-ddo#state)
=> Formatting fix

rewards/veOcean-Data-Farming-Tutorial.md
Fixes # .
- Fixes a broken link to the YT veDF tutorial video.
- 
-
=> Fixes a Broken Link to the YT veDF Tutorial Video

building-with-ocean/using-ocean-libraries/README.md
Fixes #1175
- fix ocean.js link
- 
-
=> fix ocean.js link

building-with-ocean/using-ocean-libraries/configuration.md
=> updated ocean.py doc.

api-references/provider-rest-api.md
Fixes #1143  .
- mention the document for possible provider errors.
=> Link document regarding provider errors.

building-with-ocean/deploying-components/deploying-provider.md
=> Document multichain provider.

core-concepts/networks/bridges.md
=> Embeds the mOCEAN Youtube Video

discover/networks/bridges.md
=> Embed mOCEAN Video

defi.md
- Added Predict ETH section
- Added How to Algo Trade Crypto section
- Added Create Trading Strategy NFTs section
=> Create defi page

veocean-data-farming/delegation.md
=> Fix delegation select wallet address message

discover/faq.md
=> Keshav Update faq.md

discover/faq.md
Contains tokenomics-related questions from the faq  (general jan-june 2023 ) spreadsheet that are not marked and are ready to be integrated into the docs
quantity - 53-74th cell 
Fixes # .
- 
- 
-
=> keshav tokenomics Update faq .md

discover/faq.md
This PR contains all the questions related to predictoor from this spreadsheet -https://docs.google.com/spreadsheets/d/1-E_8gV5yRl109VqvDFqWrYxjb-lmBKfc/edit#gid=1906506337
Fixes # .
- 
- 
-
=> Predictoor Faqs.md

developers/ocean.js/configuration.md, developers/ocean.js/consume-asset.md
Fixes # .
- update consume asset and configuration code example
=> Oceanjs fixes

predictoor/README.md
=> Fix #1273: Improve predictoor links. Also mild 'resources' improvement

developers/ocean-cli/install.md
Related to: https://github.com/oceanprotocol/ocean-cli/pull/29
=> Update from mnemonic to private key

discover/wallets-and-ocean.md
- Added Oasis Sapphire Mainnet & Testnet OCEAN token contract addresses
=> Add Oasis Sapphire OCEAN Token Contract Info

developers/contracts/fees.md
=> Added FRE swap fee

developers/ocean.py/README.md, developers/ocean.py/datatoken-interface-tech-details.md, developers/ocean.py/install.md, developers/ocean.py/local-setup.md, developers/ocean.py/ocean-assets-tech-details.md, developers/ocean.py/ocean-compute-tech-details.md, developers/ocean.py/remote-setup.md
=> Update ocean.py docs after brownie removal.

rewards/user-guides/how-to-volumedf.md
=> Fix #1297: DF: Volume DF Howto is cumbersome

user-guides/README.md
=> Fix #1307: broken links

data-farming/predictoordf.md
=> Fix #1371: [DF] In Volume DF, all 20 feeds are worth allocating

discover/networks/README.md, discover/wallets-and-ocean.md
addresses from https://github.com/oceanprotocol/contracts/pull/838/files
=> add optimism networks

data-farming/predictoordf.md
Fixes [72](https://app.zenhub.com/workspaces/s3-predictoor-642ce98aa2ed9d00173ef51f/issues/gh/oceanprotocol/pdr-private/72).
=> Updated ROSE rewards section

developers/subgraph/README.md, discover/networks/README.md
Added the subgraph link and also updated optimism to -> OP Mainnet as the new name is
=> Added op mainnet subgraph 

data-scientists/ocean.py/datatoken-interface-tech-details.md, data-scientists/ocean.py/local-setup.md, developers/contracts/pricing-schemas.md
Address replacement of Ganache var name from GANACHE_HARDFORK to GANACHE_FORK.
=> Replace ganache var name from HARDFORK to FORK.

data-farming/predictoordf-guide.md, data-farming/predictoordf.md
=> Fix #1410: Update Predictoor DF ROSE rewards to 20K ROSE / wk

data-farming/README.md, data-farming/apys.md, data-farming/faq.md, data-farming/predictoordf.md, data-farming/reward-schedule.md, data-farming/volumedf.md
=> Fix #1420: [DF] Update for DF Main 2

data-farming/volumedf.md
=> Fix #1430: Update Volume DF based on bug

data-farming/README.md
=> #1439: [DF] Tune docs for retired streams

data-scientists/the-data-value-creation-loop.md, developers/provider/authentication-endpoints.md, developers/provider/compute-endpoints.md, infrastructure/compute-to-data-docker-registry.md, infrastructure/compute-to-data-minikube.md
fix some typos in comment
- 
- 
-
=> chore: fix some typos in comment

discover/benefits.md
=> Update - what can you do with ocean page update.md

discover/ocean-token.md
=> Update ocean-token(Casiana suggestions).md

discover/networks/bridges.md
=> Update bridges page.md

developers/ocean-node/README.md
=> Update Ocean Nodes README (eligibility info).md

discover/faq.md
=> Update faq (fixing a small typo).md

data-farming/predictoordf.md
Updated the rewards section with new info
Fixes # .
- 
- 
-
=> Update predictoordf .md

discover/README.md
=> Fix #1511: rendering issue in 'discover' page, second line

discover/glossary.md
also, removed older outdated products like veocean
=> Updated glossary with decentralized compute terminologies .md
