oceanprotocol/docs

- content/concepts/terminology.md
I added some notes about how, initially, publishers will also be the owners of the assets they publish. I didn't want to make it seem like the two will always be combined, so I didn't delete the definition of a "Publisher."
Included "Tribes" as a synonym of Marketplaces.
Changed "Data Owner or Service Provider" to "Data Owner or Data Service Provider", in case it wasn't clear that "Data" was also modifying "Service Provider."
Resolves #55
> Fix the terminology as per issue #55

- data/repositories.yml
- data/sidebars/concepts.yml
because we're removing that page from the docs site in https://github.com/oceanprotocol/dev-ocean/pull/95
> Remove all refs to the /concepts/squid/ page

- content/concepts/terminology.md
@dgossen said he's not comfortable using "tribe" and I agree.
@aaitor When I asked Trent about this, he said we might use "tribe" internally and informally, but it shouldn't be used in official communications.
> Removed only instance of "Tribe" in this repo

- content/tutorials/get-use-compute-service.md
- content/tutorials/get-use-data-set.md
- content/tutorials/publish-compute-service.md
- content/tutorials/publish-data-set.md
So it doesn't look so empty and if we title them in sidebar there's no reason to not include the page title.
> add title to placeholder tutorials

- content/concepts/testnets.md
- content/setup/keeper.md
- content/tutorials/get-ether-and-ocean-tokens.md
I noticed that we're renaming the Trilobite/Ocean POA Testnet as the Nile Testnet, e.g. in https://github.com/oceanprotocol/keeper-contracts/pull/201
This pull request makes the same change in docs.oceanprotocol.com.
> Rename Trilobite/Ocean POA Testnet to Nile Testnet

- content/setup/marketplace.md
- content/tutorials/react-publish-data-set.md
Now that the React App Tutorial exists, we should get marketplace developers to go there first.
I also reorganized the Marketplace Setup Guide to have a more logical flow, and clarified that the Ocean Mainnet is slated to launch in March 2019.
>  Revise Marketplace Setup Guide to point to React App Tutorial

- scripts/deploy.sh
* cache everything by default
* so all files get the `public-read` ACL by default, which fixes current console errors on live
* modify cache headers for selected files afterwards
* no cache for more selected files which should make service worker updates more reliable
* be more verbose during deployment
> tweak deployment

- content/concepts/tools.md
- content/tutorials/introduction.md
- content/tutorials/jupyter-notebooks.md
- data/sidebars/tutorials.yml
- Added a new subsection to the **Tutorials** section: **squid-py Tutorials**, with one page in it so far: **Jupyter Notebooks**.
- That new **Jupyter Notebooks** page gives a quick introduction to what the Jupyter notebooks are about, links to them at https://datascience.oceanprotocol.com/ and gives some tips on how to get started with them.
- Made the **Introduction** page for the **Tutorials** section shorter and more accurate.
- Simplified the **Tools & Examples** page
- Added tuna to the list of squid-py examples
> Add link & explanation of Jupyter notebook tuts

- content/concepts/bounties.md
Link to https://github.com/oceanprotocol/openwaters on bounties page.
> add openwaters repo

- content/setup/quickstart.md
- src/components/Repositories/QuickRun.jsx
- src/components/Repositories/index.jsx
Today, if you just do:
```text
git clone https://github.com/oceanprotocol/barge.git
cd barge/
./start_ocean.sh --latest
```
as suggested on the docs.oceanprotocol.com home page (and in the Quickstart page), it won't work because Brizo needs to connect to some storage and none is set up. They must set up Azure storage first.
Before Christmas, my impression was that a local storage option was going to be added right away, and it would be the Barge default, so the above quickstart would work. Therefore I felt no need to make any changes.
Apparently that didn't happen (yet). This pull request makes changes to make the quickstart user experience better:
1. On the Quickstart page (in the Setup Guides), tell them they must set up some Azure storage first, and link to the tutorial about how to do …
> Remove homepage quickstart & fix Quickstart page

- src/components/DocContent.module.scss
- src/styles/global.scss
The prims.js styles are inlined at top of page so they clash with our own styles for inline code, which is different than what the prism.js theme provides. Solve this by increasing the specificity of our own `code` styles.
> fix aggressive prims.js syntax styles for inline code

- content/concepts/wallets.md
- content/tutorials/metamask-setup.md
This pull request makes more simplifications to the pages about wallets: the **Wallet Basics** page and the **Set Up MetaMask** page.
- The **Wallet Basics** page now begins with a short list of the wallet + storage options which I know will work for people who want to manage Ocean Tokens; there's no more waffling by giving a list of popular wallets that might or might not work. We can add more options when we're sure they'll work. Meanwhile I listed the criteria for getting on the list.
- I was testing MyEtherWallet today and it doesn't allow for connecting to a custom network (such as the Main Ocean Network will be at launch) so MyEtherWallet is not going to be an option at first. I added a note about that (and why). (I think MyEtherWallet _used to_ support connecting to custom networks …
> Simplify Wallet Basics + Metamask Tutorial pages

- content/concepts/wallets.md
- content/setup/quickstart.md
Quickstart option 2 isn't fully working right now because Barge isn't working fully right now, but as soon as it is, the Barge `README.md` file will be the first to be updated. Later, we can update the Quickstart page in the docs (which has a boiled-down version of the Barge `README.md` file).
For now, option 2 mainly just points to the Barge repo (i.e. the Barge `README.md` file).
Related: https://github.com/oceanprotocol/barge/pull/119
> Point Quickstart option 2 to Barge repo for now

- content/concepts/wallets.md
I guess we don't want to commit to there being a token bridge between the Ethereum mainnet and the Ocean mainnet. There are other options and it seems we're reviewing them again.
> Remove mention of token bridge in production

- content/concepts/tools.md
- content/tutorials/introduction.md
- content/tutorials/jupyter-notebooks.md
Revised the Examples section of the **Tools & Examples** page to have three parts, one for each of squid-py, squid-js and squid-java. Removed any mention of Tuna because it's outdated. (I confirmed that with Dimi.) Added links to the tests (for all three) because those are good examples (and must be up-to-date). 
Also:
- Removed mention of compute services in the Tutorials introduction page.
- Added link to the new data science blog post.
> Updated the Tools & Examples page

- .travis.yml
- scripts/deploy.sh
This is a follow-up to pull request #166.
It attempts to force the Travis deploy script to use Python 3 and pip3.
> Try to enforce py3 & pip3 in Travis deploy

- content/concepts/contributing.md
Remove the sub-points about adding the copyright notice and the signed-off-by line because it made it seem like that's necessary for _everyone_.
> Simplify the 'Ways to Contribute' page

- content/concepts/testnets.md
For the Kovan and Nile testnets, I added details such as:
- the RPC URL (for Nile only, MetaMask and similar already know the Kovan RPC URL)
- Links to blockchain explorers
- How to figure out the keeper contract addresses
- Other Ocean components connected to the network in question, and their URLs
Resolves #170
> Update & add details to the "Testnets" page

- content/tutorials/react-setup.md
So far I just updated the setup page of the React App Tutorial.
- Use a local Spree Testnet rather than a local Kovan node and the Kovan testnet.
- Force the use of Keeper contracts v0.8.6 and the "latest" (develop branch) of Brizo and Aquarius.
- Clarify that they need to get Spree Ether in their local MetaMask-managed account and link to the page about how to do that.
- Make the storage setup step optional.
Note: At the time of writing, the Publish and Consume flows were not working yet. This is just to get us started on that process.
> (PR) Update the React App Tutorial

- content/concepts/tools.md
- content/tutorials/get-ether-and-ocean-tokens.md
Right now, there are _no_ docs about how to get Ocean Tokens for use in testnets. This is a first pass at providing some help.
In the future, I hope we can give more concrete and specific help, but this is better than nothing.
> Add docs: how to request Ocean Tokens in testnets

- content/tutorials/react-get-use-data-set.md
- content/tutorials/react-publish-data-set.md
- content/tutorials/react-setup.md
Page 1:
- Add the "optional but recommended" step of doing `docker system prune --all --volumes`
- Did some other minor grammar and clarity edits.
Page 2:
- Add a link to page 3 at the very end (similar to page 1).
Page 3:
- Remove the notice about that page of the tutorial not working.
- Changed three instances of `await ocean.something` to `await this.ocean.something` (all in the final code listing)
- Did some minor grammar edits.
> Minor fixes in the React App Tutorial

- content/concepts/testnets.md
Based on a discussion with Don, I added some clarifications to the **Testnets** page to help developers decide which one is for them.
- For developers building on Ocean, recommend that they start with at Spree Testnet.
- Add a paragraph explaining how if you run a local Nile of Kovan node, it can take a while to sync, and why that can be a problem.
- Modified two subheadings. Changed:
- **A Spree Testnet** → **A Spree Testnet (for Local Development)**
- **A Ganache-Based Testnet** → **A Ganache-Based Testnet (for Local Development)**
- Nile now has even more aliases: "_Also known as the Beta Network or Nile Beta Network. Formerly called the Ocean POA Testnet._"
> Add help re/ whether to use Kovan, Nile or Spree

- content/tutorials/wallets-and-ocean-tokens.md
The docs do have instructions to find the latest OceanToken contract address (in Kovan and Nile), but I figured I should manually update the given addresses for the Beta Network launch.
The Kovan address of OceanToken didn't change but the Nile one did. The new Nile address is the one in the current `develop` branch (and the `v0.9.1` tag) of the keeper-contracts repository.
> Update the OceanToken address in Nile

- content/concepts/components.md
- content/concepts/terminology.md
- content/concepts/testnets.md
- content/setup/marketplace.md
- content/setup/publisher.md
- content/tutorials/example-code.md
- data/sidebars/setup.yml
- The Commons Marketplace is "new" (to the outside world) so I added documentation about it and links to it in many places.
- I re-ordered the components in the **Components** page to better-reflect the L1, L2, L3 way we think of them. I also added an entry about Commons Marketplace there.
- I realized that Pleuston and Commons Marketplace are really a front-end for a _combined_ marketplace/publisher, i.e. they are not just a front-end for a marketplace. (One can also use them to publish assets.)
- I re-did a lot of the Marketplace Setup Guide. Maybe that should have been done in its own pull request, but the Commons Marketplace is a key example of a marketplace/publisher app and so I had to mention it, and then I got carried away.
- I also deleted the sentence, "The Ocean Mainnet is …
> Document Commons Marketplace and Update Marketplace Setup Guide

- content/setup/keeper.md
- Outline how Barge can run a keeper (or several) locally
- Tell them to email us if they want to run a keeper in the Nile Testnet or Ocean Mainnet
- Link to our guide on running a keeper node in the Nile Testnet (now public, in dev-ocean)
> Update the 'Run a Keeper' page

- content/concepts/testnets.md
- content/tutorials/get-ether-and-ocean-tokens.md
Mention the faucet UI deployed within the commons marketplace as the preferred way of getting Ether for Nile. Also update faucet code examples to be consistent.
> Add faucet UI to Get Ether doc

- content/concepts/testnets.md
Remove `--local-spree-node` as this is the default in barge.
> omit node option from Spree explanation

- content/concepts/testnets.md
Git makes it look like I did a lot here but I didn't do much...
- Changed the order from Kovan-Nile-Spree-Ganache to Spree-Nile-Kovan-Ganache, to better match the order in which devs should use them.
- Changed the first paragraphs in the subsections about Spree and Nile:
**Spree:** _Formerly called Ocean Protocol Testnet v0.1, it was announced as part of the Plankton milestone._
**Nile:** _Also known as the Nile Beta Network. Formerly called the Ocean POA Testnet._
> Revised the 'Testnets' page

- content/tutorials/wallets-and-ocean-tokens.md
- data/sidebars/tutorials.yml
Make it clear that MetaMask can be used to:
- check your Ocean Token balance
- send Ocean Tokens to others
Note: Some of the labels on MetaMask buttons changed from `UPPERCASE` to `Title Case` so I also updated the instructions referencing those buttons.
> Clarify MetaMask can check Ocean bal & send tokens

- content/tutorials/example-code.md
- Removed the link to the squid-js `src/examples` directory because it is gone now, following https://github.com/oceanprotocol/squid-js/pull/231
- Added a link to the squid-js integration tests (in addition to the link to the unit tests, which was already in the docs).
- I don't think Tuna is easy for an outsider to use yet, so there are no links to Tuna. (The Tuna README.md file hasn't been updated since December.)
> Update the page with links to example squid code

- content/concepts/introduction.md
- content/concepts/ocean-tokens.md
- content/concepts/production-network.md
- content/concepts/resources.md
- content/concepts/tools.md
- content/concepts/wallets.md
- content/setup/keeper.md
- content/setup/marketplace.md
- content/tutorials/get-ether-and-ocean-tokens.md
- data/sidebars/concepts.yml
This pull request updates the terminology used for the "Ocean Production Network" (in the docs website). Before I was calling it the "Ocean Mainnet".
- Added a new page (under "Concepts") about the Ocean Production Network. It lists some other terminology that is sometimes used for that network.
- Also made some updates to the subsection about "mainnet" Ocean Tokens (including renaming that subsection).
- Also fixed a link to https://github.com/oceanprotocol/dev-ocean/blob/master/doc/devops/keeper-setup.md
> Update terminology re/ Ocean Production Network

- content/concepts/tools.md
- content/tutorials/example-code.md
- data/repositories.yml
- src/components/Repositories/Repository.jsx
Note: I added `<repo name="blockscout"></repo>` in the Tools page but it doesn't render and I'm not sure why. Maybe it's because that repo is a fork? Anyway, it's not super-important. There _is_ a hyperlink to its repo.
> Update the Tools and Example-Code Pages

- content/concepts/components.md
- data/repositories.yml
New sections for front-page repo list:
- Tools
- Osmosis Drivers
This reflects more the structure of the _Software Components_ doc.
Also added `parity-ethereum` fork cause I think this repo is what we're using to run our secret store.
Resulting in:
> split up repos list, add Osmosis, add parity fork

- content/concepts/production-network.md
Add that to the list of other names for the Ocean Production Network. (It's the name used on [the roadmap part of the website](https://oceanprotocol.com/protocol/#roadmap).)
> "The Production-Ready Ocean Network"

- content/concepts/components.md
- content/concepts/contributing.md
- content/concepts/ocean-tokens.md
- content/concepts/production-network.md
- content/concepts/resources.md
- content/concepts/terminology.md
- src/components/Repositories/index.jsx
- Changed all instances of "the Ocean network" or "the Ocean Protocol network" to "an Ocean network" or similar.
- Added a section to the **Terminology** page to define what is meant by (an) Ocean Network.
- Standardized on "EVM-compatible network".
- OEP-11 doesn't really delve into how SEAs work so I removed the sentence suggesting that it does.
- Various other minor edits. ◔ ⌣ ◔
> Updated language

- content/concepts/components.md
- content/concepts/contributing.md
- content/setup/marketplace.md
- data/repositories.yml
- Elasticsearch is becoming the default and recommended backend for Aquarius, so change the emphasis to mention it before MongoDB.
- BigchainDB isn't really supported anymore, so I removed all mention of it.
> Updates re/ Elasticsearch, MongoDB and BigchainDB

- README.md
- content/concepts/testnets.md
- gatsby-node.js
I asked Javi about these URLs this morning, so they are the latest. Some of them aren't working yet because he's still updating things.
I also added the `https://` to the start of the Faucet Server's displayed URL, to be consistent with all the other ones.
We might want to wait for them to be working before merging this pull request. On the other hand, some of the URLs listed on the currently-live docs website are now broken.
> Update the URLs of some components attached to the Nile Testnet

- content/concepts/pacific-network.md
- content/tutorials/connect-to-networks.md
- content/tutorials/wallets-and-ocean-tokens.md
This pull request should not be merged until 1) the TODO stuff (listed below) is done and 2) the Pacific Network has officially been announced to the world as being live and ready-to-use.
It documents some details of the Pacific Network such as:
- how to connect to it (e.g. the RPC URL)
- URLs of Ocean components connected to Pacific
- the OceanToken contract address in Pacific
There are still some things to do before this pull request can be merged. Search for "TODO" to find them:
- The ChainID (of the Pacific Network's blockchain)
- The Aquarius URL (but not the Commons Aquarius URL, which is already given)
- The Brizo URL (but not the Commons Brizo URL, which is already given)
- The JupyterHub URL, if there is one
> [WIP] Document some Pacific Network details

- content/concepts/components.md
- content/concepts/ocean-tokens.md
- content/concepts/pacific-network.md
- content/concepts/terminology.md
- content/concepts/testnets.md
- content/concepts/tools.md
- content/concepts/wallets.md
- content/setup/keeper.md
- content/tutorials/connect-to-networks.md
- content/tutorials/get-ether-and-ocean-tokens.md
- content/tutorials/wallets-and-ocean-tokens.md
- data/sidebars/concepts.yml
- gatsby-node.js
- src/components/DocContent.module.scss
- src/components/DocFooter.jsx
- src/templates/Swagger/index.jsx
* add Aquarius & Brizo test instances, fetch API specs from it
* remove past versions swagger hub link
* add "Get Ether for the Pacific Network"
* fix Gitter link
* prioritize Pacific when networks are mentioned, Nile after that
* remove all mentions of Kovan
Closes #286
Closes #278
> More Pacific changes

- README.md
- docs/README.md
- docs/apis.md
- docs/content.md
- docs/github.md
- docs/repositories.md
For a more clean main Readme. Split up content documentation into multiple files.
> reorganize content docs

- scripts/deploy.sh
* turns out S3 does not allow modifying cache-control headers once they are set, resulting in our 2nd part of s3sync being ignored
* fix by explicitly excluding, and then including the respective files
* should solve a bunch of cache invalidation bugs, when content is not refreshed etc.
> Fix cache-control headers

- gatsby-node.js
- package.json
- src/templates/Typedoc/Entities.jsx
- src/templates/Typedoc/Toc.jsx
- src/templates/Typedoc/utils.js
The source typedoc json is structured inconsistent so our cleanup function was omitting some stuff. This PR makes a lot more show up, consistent to what's defined in the classes array in gatsby-node.js
https://betadocs.oceanprotocol.com/references/squid-js/
closes #322
> fix typedoc cleanup

- gatsby-node.js
Refactor for getting latest squid-js github release, and filtering out pre-releases and drafts.
> Restrict squid-js API docs to production releases

- content/tutorials/react-setup.md
`localhost` replaced with live page url
> Link to connect to ocean related network fix

- data/sections.yml
"Tutorials" header still refers to React, which is obsolete#449
closes #449
> Merge fix for issue #449

- data/repositories.yml
`market-stats` will be removed, and new devs should start with the subgraph
> switch market-stats for ocean-subgraph in repo list

- gatsby-config.js
Fixes #638 .
- Fix missing image in the rendered docs.
> Fix-#638: Remove gatsby-transformer-remark plugin

- src/templates/Swagger/Paths.jsx
- src/templates/Swagger/Toc.jsx
- src/templates/Swagger/utils.js
Fixes #697 
- Group Aquarius URLs in 2 parts: 1. Starting with `/api/v1/aquarius` and `others`
There are 2 ways to fix the issue.
1st:
Show complete url in toc as below, but the urls are too long and difficult to read.
2nd:
Group urls in 2 parts as implemented in code.
> Show correct Aquarius rest endpoints

- content/concepts/networks.md
Original link is 404. If you follow their website to Technology -> Energy Web Chain, you get the replaced URL.
Sorry doing two pull requests in a row, I noticed the broken links at different times.
> Update EWT link

- content/tutorials/compute-to-data-docker-registry.md
> Issue 852 docker registry tutorials

- data/sidebars/concepts.yml
Fixes #887
- move "did & ddo" page from "Basics" to "Specifying asset"
> move "did & ddo" page from "Basics" to "Specifying asset"

- src/pages/404.jsx
Fixes #968
- Fix false negative: Dynamic pages render 404 for a short moment  before showing content
Solution reference: https://github.com/gatsbyjs/gatsby/issues/18425#issuecomment-706280750
> Add a check before rendering 404

- config.js
- gatsby-node.js
- src/components/Repository/Title.jsx
Fixes #930
- Freeze v3 versions of Ocean components
- Route to specific release version on clicking the version in home page.
> Freeze v3 version of repositories

- content/concepts/networks.md
- content/tutorials/bsc-bridge.md
Fixes #1011
Updated docs mention support for following production networks:
Mention bridge support for:
> V4: Update supported networks

- api-references/aquarius-rest-api.md
The current endpoints within the docs are not correct, or at least it doesn't seem to be. Setting the correct endpoints fix some of the calls, although I still get some errors with the first `curl` calls, probably because some stuff was moved or removed.
Fixes # .
- 
- 
-
> * Fix broken endpoints

- building-with-ocean/deploying-components/deploying-provider.md
Fixes #1110
- Update number of workers in provider deployment config
- Add hint
> Update number of providers

- SUMMARY.md
- building-with-ocean/projects-using-ocean.md
I'm proposing that we just link to the main site rather than maintaining a full list of partners on this page.
Fixes #1151
Fixes #1036 
- Adding information about service partners and link to the main site 
- changing the name and description of the page
[Preview](https://ocean-protocol.gitbook.io/partners-page/building-with-ocean/projects-using-ocean)
> Updating partners page

- SUMMARY.md
The community discord link is currently pointing to discord/invite/oceanprotocol. This brings potential failing points as the domain is available just in certain conditions.
Replaced it with the invite link we also use on the oceanprotocol website.
> Fix discord server link

- building-with-ocean/build-a-marketplace/forking-ocean-market.md
Fixes https://github.com/oceanprotocol/docs/issues/1208
- Updating documentation to remove reference to use node v16
> Updating documentation to remove reference to use node v16

- discover/networks/README.md
- discover/networks/bridges.md
Fixes #1276.
- Update the "Networks" page with information for Oasis Sapphire Mainnet & Testnet
- Update the "Bridges" page with information for Celer Bridge
- Included language to indicate that Ocean Protocol support for Oasis Sapphire networks is only for Predictoor and not ocean.js, ocean.py, nor Ocean Market.
> Add sapphire networks to solve issue 1276

- data-farming/passivedf.md
> Fix #1378: [DF] Passive DF page readability opportunities

- data-farming/apys.md
> Fix #1380: DF: APYs page should discuss how tx costs affect yield

- data-farming/volumedf.md
Fixes #1430.
- Replaced the 0.201 DCV_multiplier amount with 1.005 for Predictoor feeds per the latest announcement.
> Towards #1430: [DF] Update volumedf.md with 5x Predictoor boost DCV_multiplier
